# These are supported funding model platforms

github: [Eggy115] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: Eggy115 # Replace with a single Patreon username
open_collective: Eggy115 # Replace with a single Open Collective username
ko_fi: Eggy115  # Replace with a single Ko-fi username
tidelift: Eggy115  # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: Eggy115  # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: Eggy115  # Replace with a single Liberapay username
issuehunt: Eggy115  # Replace with a single IssueHunt username
otechie: Eggy115  # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ['https://www.youtube.com/Eggy115','https://github.com/Eggy115'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
